name: loadng
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.2+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nb_utils: ^3.3.0+7
  get_it: ^4.0.1
  http: ^0.13.1
  google_fonts: ^2.0.0
  qr_code_scanner: ^0.2.1
  mobx: ^1.2.1+2
  flutter_svg: 
  flutter_statusbarcolor: 
  image_picker: ^0.7.4
  progress_dialog: ^1.2.2
  flutter_spinkit: 4.1.0
  connectivity:
  data_connection_checker:
  streaming_shared_preferences: ^2.0.0
  firebase_messaging: ^9.1.1
  # firebase_analytics: ^5.0.11
  url_launcher: ^6.0.3
  pull_to_refresh: ^2.0.0
  intl: ^0.16.1
  qr_flutter: ^3.2.0
  flutter_inappwebview: ^5.3.2
  share:
  flutter_launcher_icons: ^0.9.0
  # firebase_crashlytics: ^0.1.3+3
  # android_intent: ^0.3.7
  # flutter_screenutil: ^1.1.0
  # firebase_dynamic_links: ^0.5.0+11
  # firebase_performance: ^0.3.1+8
  #page_transition: ^1.1.5
  # dots_indicator: ^1.1.0
  #font_awesome_flutter: ^8.8.1
  #flutter_neumorphic: ^1.0.4
  #neuomorphic_container: ^2.0.3
  #charts_flutter: ^0.9.0
  #provider_architecture: ^1.0.6
  #responsive_builder: ^0.1.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/image/logoblack.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/onboard/
    - assets/image/
    - assets/flag/
    - assets/svg/
    - assets/coins/
    - assets/fonts/

  fonts:
    - family: Plak W01 Black Condensed
      fonts:
        - asset: assets/fonts/Plak W01 Black Condensed.ttf
    
    - family: Mont Light
      fonts:
        - asset: assets/fonts/Mont-ExtraLight.otf
    
    - family: Mont Bold
      fonts:
        - asset: assets/fonts/Mont-Heavy.otf

    - family: subheader
      fonts:
        - asset: assets/fonts/subheader.ttf
 
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

    - family: Lintel
      fonts:
        - asset: assets/fonts/Lintel.ttf

    - family: Corporate Rounded
      fonts:
        - asset: assets/fonts/Corporate Rounded Bold Oblique.ttf
        - asset: assets/fonts/Corporate Rounded Oblique.ttf
        - asset: assets/fonts/Corporate Rounded Regular.ttf
        - asset: assets/fonts/Corporate Rounded Bold Oblique.ttf
        - asset: assets/fonts/Corporate Rounded Bold Oblique.ttf
    
    - family: Spinnaker
      fonts:
        - asset: assets/fonts/Spinnaker-Regular.ttf